### PR TITLE
Fixing a typo

### PR DESCRIPTION
**Pull request by katiefenn**

### CODE REVIEW

**Comment by jkbits1** [comment]
@katiefenn That's great, thanks for helping! :+1:

**Comment by jkbits1** [comment]
@PatrickHeneise Did I fail to click on merge, or was merge prevented due to CI checks

**Comment by PatrickHeneise** [comment]
@jkbits1 no idea, but now it's merged ;)

**Comment by iancrowther** [comment]
thanks @katiefenn

**Pull request merged**
