### PR TITLE
Alternative Introduction text

### PR DESCRIPTION
**Pull request by martinheidegger**
Related to #138

I took a stab at updating the readme introduction section in order for me to understand it better.

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
Good start. few minor suggestions:

- we'll try to get the github web hooks on organisation level rather than single repos
- one gitevent server manages one event (not 'multiple events')
- milestones aren't that important any more since the 'event' label automatically creates them and assigns stuff to it.

**Comment by martinheidegger** [comment]
I think I will need a specification to improve: What do you define as "event"?

**Comment by PatrickHeneise** [comment]
uhm right. If an event is defined as any kind of meet up/conference/convention, then it's multiple events, but they're all tied to an org/group, so you can't manage NodeSchool and BarcelonaJS with the same gitevents instance for example.

**Comment by iancrowther** [comment]
ola - is this merge ready or still under review?

**Pull request merged**
