### PR TITLE
[WIP] add events integration test

### PR DESCRIPTION
**Pull request by mike182uk**
This PR adds high level integration tests for the events module (`lib/events.js`).

This is an alternative approach to https://github.com/gitevents/core/pull/152

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
Very nice!

**Comment by PatrickHeneise** [comment]
I'll get rid of debug() at some point and replace with a logger, but one thing: why did you move the log after the error? It's good to see the log for a method call and then the error, otherwise you'll see an error and don't know where it's from?

**Comment by mike182uk** [comment]
@PatrickHeneise I moved the debug after the error because if an error occured, the vars you are referencing will not exist:

```
debug('GitHub:getFrom():' + sender.login); // because there was an error, sender is undefined

if (error) {
    return reject(new Error(error));
}
```

**Comment by PatrickHeneise** [comment]
right! makes sense

**Pull request merged**
